### ISSUE TITLE
Target in the report function can't be used interactively..

### ISSUE THREAD

**Issue by songlh15** [rolkra/explore#14]
Thanks for creating such an amazing package!

I'm trying to use your package in a shiny app but the report function failed to run when reactive object was passed into the function.

Suppose I have a data frame generated from reactive tabexp, this work just fine.
` report(tabexp(), output_dir = tempdir())`

However, if I wanted to use one variable from this data frame as a target, which is generated from another reactive groups, like this
` report(tabexp(), target = groups(), output_dir = tempdir())`

it won't run.

The error is 
`Error in explore(., !!sym(var_name_target)) : 
  variable 'groups()' not found`

I tried to use paste function and then get the correct target variable out, it returns another error.

`comd <- paste("report(tabexp(), target = ",groups(),",output_dir = tempdir())")
parse(comd)
Warning in file(filename, "r") :
  cannot open file 'report(tabexp(),target =  trt ,output_dir = tempdir())': No such file or directory
Error in file(filename, "r") : cannot open the connection
`
I'm wondering if this is an issue you are aware of or could you please point me the right way to use this function within interactive environment.

Thanks!

**Comment by songlh15** [comment]
It turns out not issue caused by the function. I figured it out a way to get the function works.

**Comment by sfd99** [comment]
@ songlh15 
can you share with the rest of us
how exactly you made it work ?
thanks!.
