### ISSUE TITLE
forcats 1.0.0 functionn deprecation

### ISSUE THREAD

**Issue by pinogl** [rolkra/explore#15]
Running the command `explore` I get the following warning:
`Warning: `fct_explicit_na()` was deprecated in forcats 1.0.0.
ℹ Please use `fct_na_value_to_level()` instead.
ℹ The deprecated feature was likely used in the explore package.
  Please report the issue to the authors.
`

**Comment by rolkra** [comment]
Thanks for reporting. I will fix it in the next release!
