### ISSUE TITLE
Font selection for "ggplot + theme_light()"

### ISSUE THREAD

**Issue by 419kfj** [rolkra/explore#4]
Hello, 
I am using explore with the Data which has "Japanese" Font.

I hope "ggplot + theme_light()" will accept the font selection.

In usual use of ggplot with such a Data, I write as following.

 + theme_light(base_family="sans")

I tried to use "theme_set( theme_light(base_family = "sans") ", but it did not affected to explore. If there are any way to affect this kind of setting(s) to the graph of explore, please advice to me.

Thank you for your nice package!

best.

kazuo

**Comment by rolkra** [comment]
Great that you use {explore} and that it is useful for you. explore() returns a ggplot-object, so you can just "add" a theme code to it.

```
library(magrittr)
library(explore)
iris %>% explore(Sepal.Length) + theme(text=element_text(size=16, family="serif"))
iris %>% explore(Sepal.Length) + theme(text=element_text(size=16, family="courier"))

```
You may check first which fonts are available on your system.

Does this help?

**Comment by 419kfj** [comment]
rolkra,
Thank you for your reply.
I tried as follows. If I make a single graph, it works.

But when I  generate shiny pages and report , it does not work.

# Data file "PatientStress" has Japanese col names

explore(PatientStress,ID,ストレッサー得点) + theme(text=element_text(size=12, family="sans")) # Graph with Japanese FONT OK
PatientStress %>% explore(ストレッサー得点,年齢) + theme(text=element_text(size=12, family="sans")) # Graph with Japanese FONT OK

# But
PatientStress %>% explore() + theme(text=element_text(size=12, family="sans")) # result is NULL **

# And
PatientStress %>% report(output_file = "report.html",output_dir=".") + theme(text=element_text(size=12, family="sans")) # Title in Japanese is NG.

# Also
iris %>% explore(Sepal.Length) + theme(text=element_text(size=16, family="serif")) # select font is OK.
# But
iris %>% explore() + theme(text=element_text(size=16, family="serif")) # result is NULL same as above ** 

best.

kazuo

**Comment by rolkra** [comment]
Yes, that is true. Unfortunately this "trick" does only work if you use explore() to create a single plot. If you use explore() to launch a shiny-app, use explore_all() or if you create a report, you can not control the theme and the font as it is set by {explore} to theme_light() as default.

The only hack I can think of at the moment is, to use {thematic}. I managed to change the color of the lines to red.

```
thematic::thematic_on(fg = "red") 
iris %>% explore_all()
thematic::thematic_off()
```

There seems to be an option to control the fonts, but maybe it is somehow limited to Google-Fonts (you may need to install them first). But I am not into fonts, so I guess I can't support here. Hope that helps.

I am considering to add a theme-parameter in a future verision of {explore} so that the user has control over the default theme.

**Comment by 419kfj** [comment]
rolkra,
Thank you for your confirmation.
I understand the situation.

> I am considering to add a theme-parameter in a future verision of {explore} so that the user has control over the default theme.

I am looking for this New Version ;-).

In my class, social research training, almost all students doesn't check the variable validation, and go stride to do statistical analysis.  I am looking for the EDA tool to do this important check for the data analysis. And found your package.

If you release your new version, please inform me. I will be the beta tester ;-)

regards.

kazuo

**Comment by rolkra** [comment]
I made some small changes to the code. Maybe now it works for you. Please test it using the latest github version: devtools::install_github("rolkra/explore") 

```
theme_set(theme(text=element_text(size=16, family="serif")))
explore(iris)
```

I simply dropped the theme_light() from the code. So theme_set() is not overruled.
Regards
Roland

**Comment by 419kfj** [comment]
rolkra,

Thank you for your quick support!

I did it and get Nice labels in Japanese ;-)

I attached [the capture here](https://www.evernote.com/shard/s15/sh/c51f24b6-1a03-7282-c8ca-9c4f39df9530/b6e951d24003018e94fb484459df395f).

Thank you for your support.

May I share this Github version with my college?

kazuo

**Comment by rolkra** [comment]
Great! Yes, sure you can share it. 
It may take some weeks until this changes find its way to the CRAN version
