### ISSUE TITLE
New Function Not Accessible

### ISSUE THREAD

**Issue by brichard1638** [rolkra/explore#44]
It appears that with the latest version of the explore package having been added to CRAN (version 1.2.0), the following function is not accessible, which was newly added in the latest version:

- check_vec_low_variance

This issue was identified based on the latest version of both RStudio (2023.12.1 Build 402) and R (ver. 4.3.2).

**Comment by rolkra** [comment]
Yes, this function is a internal helper function that is used by drop_var_low_variance()

If you want to drop variables in a dataset that have low variance, just use drop_var_low_variance() 
You don't need to use check_vec_low_variance()

**Comment by rolkra** [comment]
But listen it under "new features" may be misleading. I will move it in the NEWS file to "internals"

Thanks for letting me know!
