### ISSUE TITLE
[EXPLAIN] tab Tree not switching to a newly selected Var...

### ISSUE THREAD

**Issue by sfd99** [rolkra/explore#6]
_**Hi Roland!**_

Your {explore} PKG (now v: 1.0.0),
_is superb_!. 

**Problem:**
    The [EXPLAIN] tab Tree 
    is not switching to a newly selected Var 
    (chosen in the left-side Menu)...

**Steps to Reproduce Problem:**
    with 
    latest Rstudio v 576 - Ubuntu Linux 20.04 - {explore} PKG 1.0.0

  1)   library(explore)
  2)   explore(iris) 
  3)   The [VARIABLE] tab opens OK 
         with  "Sepal.Length", as default var.
  4)   I now choose from left menu:
           - target:     Species
           - variable:  **Sepal.Width**
        
       [VARIABLE] tab displays plots OK!. Good.

But...
  5)  ...when I click on the [EXPLAIN] tab,
       the decision Tree _is still showing_
       the old vars:  
                "Petal.Length" and "Petal.Width",
       _not_  the new chosen var:    **Sepal.Width**
       with target: "Species".

This happens even 
if I _again_ select_ from the left-menu
in the [EXPLAIN] tab:
           - target:     Species
           - variable:  **Sepal.Width**

The displayed Tree is still the original one,
ie: No mention at all 
  of the new selected var:  **Sepal.Width**
in the Tree in {EXPLAIN] tab.

Nothing changed in the Tree...
![image](https://user-images.githubusercontent.com/3316239/202007532-d0baee93-fe5b-490f-a870-57b094c30838.png)

Help!
What am I missing?...

**sfd99
latest Rstudio v 576 - Ubuntu Linux 20.04 - explore PKG 1.0.0
San Francisco**

**Comment by rolkra** [comment]
Thank you for using {explore} und giving feedback. The behavior you describe is wanted, as explain only uses the selected target (what to explain). All variables (not only the selected one) can be used by the decision tree to explain the target.

If you just want to explore the relationship between one specific variable and a target, simply use [Variable] tab.

**Comment by rolkra** [comment]
It is not a bug, as explain is designed to be multivariate analysis.

**Comment by sfd99** [comment]
Ah, undestand!.
_Thanks/Danke, Roland._
