### ISSUE TITLE
Artificial Data Error

### ISSUE THREAD

**Issue by brichard1638** [rolkra/explore#9]
The argument titled, 'factorise_target,' which exists in functions create_data_buy and create_data_random does not work as described. Both functions however, work as expected when this argument is not used.

Replicate error:
library(explore)
x = create_data_random(
  obs = 200,
  vars = 8,
  target_name = "buy",
  target1_prob = 0.4,
  add_id = FALSE,
  seed = 123,
  factorise_target = TRUE
)

The function returns the following error:
Error in `$<-.data.frame`(`*tmp*`, "buy", value = integer(0)) : 
  replacement has 0 rows, data has 200

**Comment by rolkra** [comment]
Thanks, I will fix it in the next version

**Comment by rolkra** [comment]
fixed version: explore 1.0.2 on CRAN
